name: Deploy to GCP
on:
  push:
    branches:
      - main
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load Google credentials into file
        run: echo $GCLOUD_CREDENTIALS > gcloud-service-key.json

      - name: Set env var for Google credentials
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=gcloud-service-key.json" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialise Terraform
        run: terraform init

      - name: Format Terraform check
        run: terraform fmt -check

      - name: Plan Terraform
        run: terraform plan
        env:
          TF_VAR_GCLOUD_PROJECT: ${{ secrets.TF_VAR_GCLOUD_PROJECT }}
