name: Deploy to GCP
on: push

env:
  PROJECT_ID: ${{ secrets.TF_VAR_GCLOUD_PROJECT }}
  IMAGE_TAG: gcr.io/${{ secrets.TF_VAR_GCLOUD_PROJECT }}/sadl-mastodon

jobs:
  cloudbuild:
    name: Build image in Cloud Build
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Build
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "$IMAGE_TAG:$GITHUB_SHA"

  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: Production
    needs: cloudbuild

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add image name to env
        run: echo "TF_VAR_RUN_IMAGE=${IMAGE_TAG}:${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialise Terraform
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Format Terraform check
        run: terraform fmt -check

      - name: Plan Terraform
        run: terraform plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_GCLOUD_PROJECT: ${{ secrets.TF_VAR_GCLOUD_PROJECT }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_GCLOUD_PROJECT: ${{ secrets.TF_VAR_GCLOUD_PROJECT }}
