name: Deploy to GCP
on:
  push:
    branches:
      - main
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialise Terraform
        run: terraform init

      - name: Format Terraform check
        run: terraform fmt -check

      - name: Plan Terraform
        run: terraform plan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          TF_VAR_GCLOUD_PROJECT: ${{ secrets.TF_VAR_GCLOUD_PROJECT }}
